// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? "Error",
    appId: dotenv.env['FIREBASE_APP_ID'] ?? "Error",
    messagingSenderId: dotenv.env['MESSAGE_SENDER_ID'] ?? "Error",
    projectId: dotenv.env['PROJECT_ID'] ?? "Error",
    authDomain: dotenv.env['AUTH_DOMAIN'] ?? "Error",
    storageBucket: dotenv.env['STORAGE_BUCKET'] ?? "Error",
    measurementId: dotenv.env['MEASUREMENT_ID'] ?? "Error",
  );
}
