// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmR0zgdFXWNen7Yq2sY_k0Y-zm8jZ9ws',
    appId: '1:226360493782:web:214d19a60a575a72b2ab77',
    messagingSenderId: '226360493782',
    projectId: 'agenda-wizard-dev',
    authDomain: 'agenda-wizard-dev.firebaseapp.com',
    storageBucket: 'agenda-wizard-dev.firebasestorage.app',
    measurementId: 'G-9LWGQHEFSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATj99TGIuaCBNKuo7cm3zBtmaeQtdmR2g',
    appId: '1:226360493782:android:299493a76c7e5bf3b2ab77',
    messagingSenderId: '226360493782',
    projectId: 'agenda-wizard-dev',
    storageBucket: 'agenda-wizard-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5b9fPsF0Crlo_9gfBT-JfZt9xM9Cv07w',
    appId: '1:226360493782:ios:992384fa3abe72c8b2ab77',
    messagingSenderId: '226360493782',
    projectId: 'agenda-wizard-dev',
    storageBucket: 'agenda-wizard-dev.firebasestorage.app',
    iosBundleId: 'com.example.agendaWizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5b9fPsF0Crlo_9gfBT-JfZt9xM9Cv07w',
    appId: '1:226360493782:ios:992384fa3abe72c8b2ab77',
    messagingSenderId: '226360493782',
    projectId: 'agenda-wizard-dev',
    storageBucket: 'agenda-wizard-dev.firebasestorage.app',
    iosBundleId: 'com.example.agendaWizard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNmR0zgdFXWNen7Yq2sY_k0Y-zm8jZ9ws',
    appId: '1:226360493782:web:50fcc6b7e9bae883b2ab77',
    messagingSenderId: '226360493782',
    projectId: 'agenda-wizard-dev',
    authDomain: 'agenda-wizard-dev.firebaseapp.com',
    storageBucket: 'agenda-wizard-dev.firebasestorage.app',
    measurementId: 'G-NYMFB0F3FV',
  );
}
